### ISSUE TITLE
[Bug] Newest release doesn't hide the window on startup

### ISSUE THREAD

**Issue by etherealxx** [MrDavidRios/remindr_releases#8]
Please take a look at the example here: https://youtu.be/6eb5GobjAEA

My computer boots up, but it needs time before it could connects to internet, right?
First the window shows up, even though i set it to hide on startup. Next, it acts as if i didn't have the account at all. Only when i close it and reopen it, it logs with my account successfully.
My suggestion is, the app, after pc boots up, when it doesn't detects a connection, sets up some grace period, like 30 seconds, before checking internet connection again. only after 3 cycles, it will make a popup on the right corner on the screen (not the whole app appearing) showing that you don't have internet connection to sync to cloud (this popup also should has an option to be disabled).

This app is amazing, you did a great job, that's why i'm still using it. I hope you could spend your free time fixing it. No pressure🙏

**Comment by MrDavidRios** [comment]
Thanks for recording a video $\textemdash$ it's very helpful. You've reported two separate bugs:

### 1. The app starts up regardless of having the 'hide window on startup' setting enabled

I haven't been able to recreate this. I'm suspicious that since I rewrote how settings were synced in [v2.1.3](https://github.com/MrDavidRios/remindr_releases/releases/tag/v2.1.3), this setting value didn't properly carry over between updates on your system. I recommend disabling and re-enabling the setting to make sure that it works properly.

To be 100% sure that the 'hide on startup' setting is not working, go to Task Manager $\rightarrow$ Startup Apps and find Remindr. It should have an 'Enabled' status and have '--hidden' at the end of its corresponding command line argument, like this:

![image](https://github.com/MrDavidRios/remindr_releases/assets/52746497/361909b2-45fe-450a-950c-6bad5edb1b13)

If it doesn't, this is a valid bug if toggling the 'hide on startup' setting doesn't toggle the '--hidden' flag on the command line startup argument.

### 2. App shows 'intro/setup' page on startup

This seems to be a bug with how Remindr handles an intermediate state where the account has been successfully verified _(login was successful)_ and there was an error loading user data for some reason. 

If there was no internet connection, neither of these screens would be shown - most likely, the loading screen would be briefly shown and then a 'connection attempt' screen like this would be shown.

![image](https://github.com/MrDavidRios/remindr_releases/assets/52746497/b9b84835-33a7-427e-9aaa-5d08310c00cc)

I'll try to reproduce this second bug $\textemdash$ I wanted to give an update on the 'hide on startup' issue in the meantime.

**Comment by etherealxx** [comment]
Hey, sorry for the late late followup.

So apparently, somehow, there are 2 startup item when i checked task manager. Maybe it's from your older version that stays? idk. So that's why i turn off startup and it's still going, because there's another startup. So i turned off the supposedly older one and now it's working great so far
![Screenshot 2024-01-17 035810](https://github.com/MrDavidRios/remindr_releases/assets/64251396/50448a7b-dd6a-4c96-b068-872aa4bc13a2)

btw my task manager (Win11 latest) doesn't have that part😅
![image](https://github.com/MrDavidRios/remindr_releases/assets/64251396/380c6c31-878a-4d50-85c9-261f29aed684)
